services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: crtrcod
      POSTGRES_PASSWORD: crtrcod
      POSTGRES_DB: crtrcod
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    networks: ["crtrcod-net"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    networks: ["crtrcod-net"]
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow server --host 0.0.0.0 --port 5000
    ports: ["5000:5000"]
    networks: ["crtrcod-net"]
  adminer:
    image: adminer
    ports: ["8080:8080"]
    networks: ["crtrcod-net"]
volumes:
  pgdata:
networks:
  crtrcod-net:
    driver: bridge
